# Generated by Django 5.0.3 on 2024-04-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('debut', models.CharField(max_length=50)),
                ('fin', models.CharField(max_length=500)),
                ('imgligne', models.CharField(max_length=5000)),
            ],
        ),
    ]
